import type { Metadata } from 'next';
import PrivateLabelCategoryLanding from '@/components/PrivateLabelCategoryLanding';

const siteUrl = 'https://peakmotionsocks.com';
const pageUrl = `${siteUrl}/custom-pilates-yoga-socks`;
const faqs = [
  ['Can you make Pilates and yoga socks with custom silicone grip?', 'Yes. We can discuss grip-dot placement, coverage, colors, logo methods and the appropriate construction for studio, Pilates, yoga and barre applications.'],
  ['Can I create a studio-ready private label collection?', 'Yes. A collection can combine selected silhouettes, colors, sizes, labels and retail packaging around your studio or wellness brand.'],
  ['Can I approve a sample before bulk production?', 'Yes. We use sampling to review the main construction, color, fit and branding details before bulk production begins.'],
  ['Do you support custom packaging?', 'Yes. Individual bags, belly bands, hang tags, header cards and retail boxes can be discussed as part of the project brief.'],
] as const;

export const metadata: Metadata = {
  title: 'Custom Pilates & Yoga Socks Manufacturer | Private Label Grip Socks | PeakMotion',
  description: 'Private label Pilates, yoga and studio grip socks with custom silicone patterns, logos, materials and retail packaging for wellness brands and studios.',
  alternates: { canonical: pageUrl },
};

export default function CustomPilatesYogaSocksPage() {
  const structuredData = { '@context': 'https://schema.org', '@graph': [{ '@type': 'WebPage', '@id': `${pageUrl}#webpage`, url: pageUrl, name: 'Custom Pilates & Yoga Socks Manufacturer | PeakMotion', description: metadata.description, about: ['Private label Pilates socks', 'Custom yoga socks', 'Studio grip socks'] }, { '@type': 'FAQPage', mainEntity: faqs.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) }] };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, '\\u003c') }} /><PrivateLabelCategoryLanding eyebrow="Private label studio sock manufacturer" title="Custom Pilates, Yoga and Studio Socks for Your Brand" description="Develop grip and studio socks for Pilates, yoga, barre and wellness collections with custom colors, silicone patterns, logos and retail-ready packaging." heroImage="/assets/products/low-cut-yoga-pilates-grip-socks/hero.png" heroAlt="Custom Pilates and yoga grip socks" productsTitle="A studio-sock range built around your customers" productsIntro="Choose a focused grip sock or develop a coordinated wellness collection with the fit, traction and visual identity your brand needs." productItems={[['Low-Cut Pilates Grip Socks', 'A compact studio silhouette with silicone traction and custom branding.', '/products/low-cut-yoga-pilates-grip-socks'], ['Open-Top Studio Socks', 'Breathable, flexible studio socks for Pilates, yoga and wellness use.', '/products/open-top-pilates-studio-socks'], ['Custom Yoga Grip Socks', 'Grip coverage, colors and logo placement developed around your yoga collection.', '/custom-grip-socks'], ['Studio Retail Packs', 'Private-label labels and packaging for studios, retailers and wellness brands.', '/custom-grip-socks#quote']]} customizationTitle="Create socks that fit your studio, movement and brand" customizationIntro="Review construction, materials, grip coverage and presentation before sampling so the product matches the intended customer and retail position." customizationItems={[['Grip Pattern', 'Specify silicone placement, coverage and logo-based details for the intended movement.'], ['Materials and Feel', 'Review yarn blend, terry cushioning, breathability and stretch for comfort and stability.'], ['Brand Colors and Logo', 'Apply custom colors and select a practical logo method for the chosen sock construction.'], ['Packaging and Size Sets', 'Plan individual packs, retail presentation and size assortments for your collection.']]} processTitle="From studio concept to private-label socks" processItems={[['Share Your Brief', 'Tell us your studio, target customer, logo, product idea and quantity.'], ['Review Construction', 'Confirm the silhouette, materials, grip direction and packaging options.'], ['Approve a Sample', 'Review fit, color, comfort and branding before the production run.'], ['Produce and Pack', 'Complete the approved specifications, quality checks and final packaging.']]} faqs={faqs} whatsappUrl="https://wa.me/8617357769219?text=Hello%20PeakMotion%20Socks%2C%20I%20would%20like%20to%20develop%20custom%20Pilates%20or%20yoga%20socks." /></>;
}
