import Link from 'next/link';
import { ProductQuickFacts, productSeo } from '@/lib/product-seo';

const assetPath = '/assets/products/jacquard-custom-socks';
const message = encodeURIComponent('Hello PeakMotion Socks, I am interested in your Jacquard Custom Socks.');
const product = productSeo['jacquard-custom-socks'];

const specifications = [
  ['Material', 'Combed cotton / polyester / spandex'],
  ['Type', 'Jacquard casual crew socks'],
  ['Design', 'Custom pattern or embroidery'],
  ['Comfort', 'Breathable soft knit'],
  ['Logo', 'Jacquard / embroidery / print'],
  ['MOQ', '50 pairs'],
  ['Packing', 'Custom packaging available'],
];

const faqs = [
  ['What artwork works best for custom jacquard socks?', 'Bold logos, stripes, repeat patterns, lettering and simplified illustrations translate most reliably into knitted jacquard. Share vector artwork or a clear reference image so we can review stitch detail, color changes and placement before sampling.'],
  ['What is the difference between jacquard and embroidery?', 'Jacquard artwork is knitted into the sock as part of the construction, making it suitable for all-over patterns, logos and color blocking. Embroidery is added after knitting and is better for selected raised details, but it has more limits around stretch areas.'],
  ['Which material blend should I choose?', 'Combed cotton is a common choice for a soft casual handfeel. Polyester or nylon can add durability and color performance, while spandex helps the sock recover after wear. The right blend depends on the use case, desired price point and design.'],
  ['Can I order custom packaging with the socks?', 'Yes. We can discuss bulk packing, paper bands, header cards, barcode labels, backer cards, multipacks and custom boxes as part of the quotation and sample approval process.'],
  ['How long do samples and bulk production take?', 'Samples are typically prepared in about 7 days after the specification is confirmed. Standard bulk production is usually 25-30 days after sample approval, with timing confirmed against your final design, quantity and packaging requirements.'],
] as const;

export default function JacquardCustomSocksPage() {
  return (
    <main className="bg-white text-[#0c1713]">
      <section className="mx-auto grid max-w-[1440px] grid-cols-1 items-center gap-10 px-5 py-12 md:px-8 lg:grid-cols-[1.05fr_0.95fr] lg:gap-16 lg:py-20">
        <div className="rounded-[28px] bg-[#f7f8f6] p-5 md:p-10">
          <img src={`${assetPath}/hero.jpg`} alt="Jacquard custom crew socks" className="h-auto w-full object-contain" />
        </div>
        <div className="max-w-xl space-y-6">
          <span className="inline-flex rounded-full bg-[#e9f8d2] px-4 py-2 text-xs font-black tracking-[0.16em] text-[#387116]">CUSTOM DESIGN</span>
          <h1 className="text-4xl font-black leading-tight md:text-6xl">Jacquard Custom Socks</h1>
          <p className="text-lg leading-relaxed text-slate-600">Custom crew socks for private-label brands, clubs and retailers that need knitted logos, repeat patterns, considered yarn blends and launch-ready packaging. We help turn a practical artwork brief into a wearable product specification.</p>
          <ProductQuickFacts product={product} />
          <a href={`https://wa.me/8617357769219?text=${message}`} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center rounded-xl bg-[#39a91f] px-7 py-4 font-black uppercase tracking-wide !text-white transition-all hover:-translate-y-0.5 hover:bg-[#2f8b19] hover:shadow-lg">Chat on WhatsApp</a>
        </div>
      </section>

      <section className="border-y border-slate-100 bg-[#fbfcfa] py-12"><div className="mx-auto max-w-[1200px] space-y-8 px-5 md:px-8"><img src={`${assetPath}/features.jpg`} alt="Jacquard sock core features" className="h-auto w-full" /><img src={`${assetPath}/product-features.jpg`} alt="Jacquard sock product features" className="h-auto w-full" /></div></section>

      <section className="mx-auto grid max-w-[1200px] grid-cols-1 gap-12 px-5 py-20 md:px-8 lg:grid-cols-2">
        <div><p className="mb-3 text-sm font-black uppercase tracking-[0.15em] text-[#679a20]">Product Details</p><h2 className="text-3xl font-black md:text-4xl">Specifications</h2><dl className="mt-8 overflow-hidden rounded-2xl border border-slate-200">{specifications.map(([label, value]) => <div key={label} className="grid grid-cols-[110px_1fr] gap-4 border-b border-slate-200 px-5 py-4 last:border-b-0"><dt className="font-bold">{label}</dt><dd className="text-slate-600">{value}</dd></div>)}</dl></div>
        <div><p className="mb-3 text-sm font-black uppercase tracking-[0.15em] text-[#679a20]">OEM Service</p><h2 className="text-3xl font-black md:text-4xl">Your artwork, made wearable</h2><p className="mt-5 text-lg leading-relaxed text-slate-600">We review the art file, intended wearer, sock height, color direction and packaging needs before sampling. This gives the factory a clear instruction and gives your team a product they can explain, launch and reorder.</p><img src={`${assetPath}/oem.jpg`} alt="OEM jacquard sock customization" className="mt-8 h-auto w-full rounded-2xl" /></div>
      </section>

      <section className="border-y border-slate-100 bg-[#fbfcfa] py-20"><div className="mx-auto max-w-[1200px] px-5 md:px-8"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.15em] text-[#679a20]">Built For Your Buyer</p><h2 className="mt-3 text-3xl font-black md:text-4xl">A custom crew sock can support more than one collection</h2><p className="mt-5 text-lg leading-relaxed text-slate-600">The strongest brief starts with the buyer, not just the logo. Tell us where the sock will be sold or worn so we can review construction, yarn feel and packaging against the intended use.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Private-label brands', 'Create a recognizable core crew sock with knitted identity and retail-ready details.'], ['Clubs and events', 'Develop team colors, sponsor placement and participant or merchandise packs.'], ['Retailers and wholesalers', 'Plan readable size ranges, SKUs, labels and carton sorting for your channel.'], ['Lifestyle collaborations', 'Translate a visual campaign, artist work or seasonal palette into a wearable pattern.']].map(([title, text]) => <div key={title} className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">{text}</p></div>)}</div></div></section>

      <section className="mx-auto grid max-w-[1200px] grid-cols-1 gap-12 px-5 py-20 md:px-8 lg:grid-cols-2"><div><p className="text-sm font-black uppercase tracking-[0.15em] text-[#679a20]">Pattern And Materials</p><h2 className="mt-3 text-3xl font-black md:text-4xl">Make the artwork work with the knit</h2><p className="mt-5 text-lg leading-relaxed text-slate-600">Jacquard is created during knitting, so stitch scale, yarn colors and logo placement all influence the final result. We review the artwork before sampling to help avoid fine lines, small lettering or high-detail areas that may not read clearly after the sock stretches.</p><div className="mt-7 space-y-4">{[['Jacquard patterns and logos', 'Best for stripes, color blocks, repeat motifs, clear lettering and knitted logos that are integrated into the sock.'], ['Material direction', 'Choose combed cotton for softness, add polyester or nylon when durability and color performance matter, and use spandex for stretch recovery.'], ['Embroidery and print accents', 'These can suit selected decorative details, but we will confirm placement and stretch limitations before they become part of the sample.']].map(([title, text]) => <div key={title} className="rounded-2xl border border-slate-200 p-5"><h3 className="font-black">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{text}</p></div>)}</div></div><div className="rounded-[28px] bg-[#07120c] p-7 text-white md:p-10"><p className="text-sm font-black uppercase tracking-[0.15em] text-[#b4ff2b]">Artwork Checklist</p><h2 className="mt-3 text-3xl font-black">Send a brief a factory can use</h2><ul className="mt-7 space-y-4 text-slate-200">{['Vector logo or clear reference artwork', 'Target sock height, size range and intended customer', 'Color references and preferred yarn or handfeel', 'Pattern placement, label requirements and packaging format', 'Quantity, destination and desired delivery date'].map((item) => <li key={item} className="flex gap-3"><span className="font-black text-[#b4ff2b]">✓</span><span>{item}</span></li>)}</ul><Link href="/blog/custom-running-socks-oem-guide" className="mt-8 inline-flex font-black text-[#b4ff2b] underline underline-offset-4">See how a production-ready OEM brief is built</Link></div></section>

      <section className="bg-[#f7f8f6] py-20"><div className="mx-auto max-w-[1200px] px-5 md:px-8"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.15em] text-[#679a20]">Order Planning</p><h2 className="mt-3 text-3xl font-black md:text-4xl">Confirm the route from first brief to bulk order</h2><p className="mt-5 text-lg leading-relaxed text-slate-600">MOQ, sample review and packaging are connected decisions. Confirming them early gives your team a clearer production instruction and a more realistic delivery plan.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[['1. Quote and artwork review', 'Share the product goal, quantity, artwork, size range, colors, packaging and destination. We review the construction and quote direction.'], ['2. Sample approval', 'Review the sample for fit, color direction, pattern clarity, logo placement and packaging details before authorizing bulk production.'], ['3. Production and packing', 'Standard bulk production is usually 25-30 days after approval. Final timing depends on the confirmed design, quantity and packaging.']].map(([title, text]) => <div key={title} className="rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><h3 className="text-xl font-black">{title}</h3><p className="mt-4 text-sm leading-relaxed text-slate-600">{text}</p></div>)}</div><div className="mt-8 rounded-2xl border border-[#cfe8a7] bg-[#eff9df] p-6"><h3 className="font-black">Packaging can be part of the same brief</h3><p className="mt-2 leading-relaxed text-slate-700">Options can include bulk packing, paper bands, barcode labels, header cards, backer cards, multipacks and custom boxes. State your sales channel so the packaging recommendation suits how the product will be used or displayed.</p></div></div></section>

      <section className="bg-[#f7f8f6] py-20"><div className="mx-auto max-w-[1200px] space-y-14 px-5 md:px-8"><div className="text-center"><p className="text-sm font-black uppercase tracking-[0.15em] text-[#679a20]">Custom Options</p><h2 className="mt-3 text-3xl font-black md:text-4xl">Colors, applications and factory support</h2></div>{['colors.jpg', 'applications.jpg', 'factory.jpg', 'certifications.jpg'].map((image) => <img key={image} src={`${assetPath}/${image}`} alt="Jacquard custom sock product information" className="h-auto w-full rounded-2xl bg-white" />)}</div></section>

      <section className="mx-auto max-w-[1000px] px-5 py-20 md:px-8"><p className="text-sm font-black uppercase tracking-[0.15em] text-[#679a20]">FAQ</p><h2 className="mt-3 text-3xl font-black md:text-4xl">Questions from custom jacquard sock buyers</h2><div className="mt-8 divide-y divide-slate-200 overflow-hidden rounded-2xl border border-slate-200">{faqs.map(([question, answer]) => <details key={question} className="bg-white px-6 py-5"><summary className="cursor-pointer font-black">{question}</summary><p className="mt-3 max-w-3xl leading-relaxed text-slate-600">{answer}</p></details>)}</div><div className="mt-10 rounded-2xl bg-[#eff9df] p-7"><h2 className="text-2xl font-black">Planning a private-label launch?</h2><p className="mt-3 max-w-2xl leading-relaxed text-slate-700">Use our running socks articles to structure the brand, product and production parts of your brief before you request a quotation.</p><div className="mt-5 flex flex-col gap-3 sm:flex-row"><Link href="/blog/private-label-running-socks-brand-guide" className="font-black text-[#387116] underline underline-offset-4">Read the private-label launch guide</Link><Link href="/blog/custom-running-socks-oem-guide" className="font-black text-[#387116] underline underline-offset-4">Read the OEM planning guide</Link></div></div></section>

      <section id="quote" className="relative overflow-hidden bg-[#07120c] px-5 py-20 md:px-8 md:py-28"><div className="absolute inset-0"><img src={`${assetPath}/cta.jpg`} alt="Custom jacquard crew socks" className="h-full w-full object-cover opacity-45" /><div className="absolute inset-0 bg-gradient-to-r from-[#07120c] via-[#07120c]/90 to-[#07120c]/45" /></div><div className="relative mx-auto max-w-7xl"><div className="max-w-2xl space-y-7 text-left text-white"><h2 className="text-4xl font-black uppercase leading-tight md:text-6xl">Ready to Build <br />Your Sock Brand?</h2><p className="text-xl font-medium text-gray-200 md:text-2xl">Contact us today and get a free quote within 24 hours.</p><div className="flex flex-col gap-5 pt-3 sm:flex-row"><a href={`https://wa.me/8617357769219?text=${message}`} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center rounded-2xl bg-[#b4ff2b] px-10 py-5 text-lg font-black uppercase text-black shadow-2xl transition-transform hover:scale-105">Get Quote Now</a><a href="https://wa.me/8617357769219" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center rounded-2xl border-2 border-white bg-white/10 px-10 py-5 text-lg font-black uppercase !text-white backdrop-blur-md transition-all hover:bg-white hover:!text-black">Chat on WhatsApp</a></div></div></div></section>
    </main>
  );
}
